Description: This template includes infrastructure, modelFunction infrastructure and
  get label infrastructure
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    DependsOn:
    - ModelFunctionLambdaImageBucket
    - ModelFunctionLambda
    Properties:
      BucketName:
        Fn::Sub: image-logoapplication-${AWS::AccountId}
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: s3:ObjectCreated:Put
          Filter:
            S3Key:
              Rules:
              - Name: suffix
                Value: .jpg
          Function:
            Fn::GetAtt:
            - ModelFunctionLambda
            - Arn
        - Event: s3:ObjectCreated:Put
          Filter:
            S3Key:
              Rules:
              - Name: suffix
                Value: .png
          Function:
            Fn::GetAtt:
            - ModelFunctionLambda
            - Arn
      CorsConfiguration:
        CorsRules:
        - AllowedOrigins:
          - Fn::GetAtt:
            - WebsiteBucket
            - WebsiteURL
          AllowedMethods:
          - PUT
          AllowedHeaders:
          - '*'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  GetRestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: scalableLogo-GetRestAPI
  GetRestAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: GetRestAPI
      ParentId:
        Fn::GetAtt:
        - GetRestAPI
        - RootResourceId
      PathPart: get-url
  GetRestAPIMethod:
    DependsOn: GetLambdaAPIPermission
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: GetRestAPIResource
      RestApiId:
        Ref: GetRestAPI
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetLambda.Arn}/invocations
        IntegrationResponses:
        - StatusCode: 200
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: Empty
        ResponseParameters:
          method.response.header.Access-Control-Allow-Origin: false
  GetRestAPIMethodOptions:
    DependsOn: GetLambdaAPIPermission
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: GetRestAPIResource
      RestApiId:
        Ref: GetRestAPI
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
            method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS'''
            method.response.header.Access-Control-Allow-Origin: '''*'''
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: Empty
        ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: false
          method.response.header.Access-Control-Allow-Methods: false
          method.response.header.Access-Control-Allow-Origin: false
  LabelRestAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: GetRestAPI
      ParentId:
        Fn::GetAtt:
        - GetRestAPI
        - RootResourceId
      PathPart: get-label
  LabelRestAPIMethod:
    DependsOn: GetLambdaAPIPermission
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: LabelRestAPIResource
      RestApiId:
        Ref: GetRestAPI
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetLambda.Arn}/invocations
        IntegrationResponses:
        - StatusCode: 200
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: Empty
        ResponseParameters:
          method.response.header.Access-Control-Allow-Origin: false
  LabelRestAPIMethodOptions:
    DependsOn: GetLambdaAPIPermission
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: LabelRestAPIResource
      RestApiId:
        Ref: GetRestAPI
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
            method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS'''
            method.response.header.Access-Control-Allow-Origin: '''*'''
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: Empty
        ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: false
          method.response.header.Access-Control-Allow-Methods: false
          method.response.header.Access-Control-Allow-Origin: false
  GetRestAPIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: GetRestAPI
      StageName: prod
      DeploymentId:
        Ref: GetRestAPIDeployment
  GetRestAPIDeployment:
    DependsOn:
    - GetRestAPIMethod
    - GetRestAPIMethodOptions
    - LabelRestAPIMethod
    - LabelRestAPIMethodOptions
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: GetRestAPI
  GetLambdaAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName:
        Fn::GetAtt:
        - GetLambda
        - Arn
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GetRestAPI}/*
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: lambdaSignURL
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:PutObjectAcl
            Resource:
            - Fn::Sub: arn:aws:s3:::image-logoapplication-${AWS::AccountId}/*
          - Effect: Allow
            Action: dynamodb:GetItem
            Resource:
              Fn::GetAtt:
              - OutputDatabase
              - Arn
  GetLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: logoapplication-lambdafiles-34fl9as0
        S3Key: 1d9030d05f7f0df44a04d7516fd977a8
      FunctionName: logoApplicationGetter
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: nodejs8.10
      Timeout: 10
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          uploadBucket:
            Fn::Sub: image-logoapplication-${AWS::AccountId}
          TableName:
            Ref: OutputDatabase
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: logoapplication-website-39bk35l8
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource:
            Fn::Sub: ${WebsiteBucket.Arn}/*
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: logoapplication-website-39bk35l8
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html
  PreparationBucket:
    Type: AWS::S3::Bucket
    Properties: {}
  OutputDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: ImageId
        AttributeType: S
      KeySchema:
      - AttributeName: ImageId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  PytorchLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
      - python3.6
      Content:
        S3Bucket: logoapplication-lambdafiles-34fl9as0
        S3Key: a0c79649eb07d80d375b9622c45887df
  ModelFunctionLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: lambdaModelFunction
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:ListBucket
            Resource:
            - Fn::Sub: ${PreparationBucket.Arn}/*
            - Fn::Sub: ${PreparationBucket.Arn}
            - Fn::Sub: arn:aws:s3:::image-logoapplication-${AWS::AccountId}/*
            - Fn::Sub: arn:aws:s3:::image-logoapplication-${AWS::AccountId}
          - Effect: Allow
            Action: dynamodb:PutItem
            Resource:
              Fn::GetAtt:
              - OutputDatabase
              - Arn
  ModelFunctionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: logoapplication-lambdafiles-34fl9as0
        S3Key: d02f06e2e93d4705e6cafe19a62b8ba8
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
        - ModelFunctionLambdaRole
        - Arn
      Runtime: python3.6
      Layers:
      - Ref: PytorchLambdaLayer
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          TableName:
            Ref: OutputDatabase
          image_bucket:
            Fn::Sub: image-logoapplication-${AWS::AccountId}
          preparation_bucket:
            Ref: PreparationBucket
  ModelFunctionLambdaImageBucket:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - ModelFunctionLambda
        - Arn
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::image-logoapplication-${AWS::AccountId}
Outputs:
  GetAPIURL:
    Description: URL of get API
    Value:
      Fn::Sub: https://${GetRestAPI}.execute-api.${AWS::Region}.amazonaws.com/prod
    Export:
      Name: GetApiURL
  WebsiteUrl:
    Description: URL of the website
    Value:
      Fn::GetAtt:
      - WebsiteBucket
      - WebsiteURL
    Export:
      Name: WebsiteURL
  PreparationBucketName:
    Description: Name of bucket to dump preparation files
    Value:
      Ref: PreparationBucket
    Export:
      Name: PrepBucketName
