Resources:
  ImageBucket:
    Properties: {}
    Type: AWS::S3::Bucket
  ModelFunctionLambda:
    Properties:
      Code:
        S3Bucket: logoapplication-lambdafiles-34fl9as0
        S3Key: 363a2f296e3210ff2e59a83b1b44d8de
      Environment:
        Variables:
          TableName:
            Ref: OutputDatabase
          image_bucket:
            Ref: ImageBucket
          preparation_bucket:
            Ref: PreparationBucket
      FunctionName: logoApplicationModelFunction
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
        - ModelFunctionLambdaRole
        - Arn
      Runtime: python3.6
    Type: AWS::Lambda::Function
  ModelFunctionLambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: 2012-10-17
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          - Action: s3:GetObject
            Effect: Allow
            Resource:
            - Fn::Sub: ${PreparationBucket.Arn}/*
            - Fn::Sub: ${ImageBucket.Arn}/*
          - Action: dynamodb:PutItem
            Effect: Allow
            Resource:
              Fn::GetAtt:
              - OutputDatabase
              - Arn
          Version: 2012-10-17
        PolicyName: lambdaModelFunction
    Type: AWS::IAM::Role
  OutputDatabase:
    Properties:
      AttributeDefinitions:
      - AttributeName: ImageId
        AttributeType: S
      - AttributeName: Timestamp
        AttributeType: N
      KeySchema:
      - AttributeName: ImageId
        KeyType: HASH
      - AttributeName: Timestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
    Type: AWS::DynamoDB::Table
  PreparationBucket:
    Properties: {}
    Type: AWS::S3::Bucket
