Resources:
  PreparationBucket:
    Type: AWS::S3::Bucket
    Properties: {}

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties: {}

  OutputDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: ImageId
          AttributeType: S
        - 
          AttributeName: Timestamp
          AttributeType: N
      KeySchema:
        -
         AttributeName: ImageId
         KeyType: HASH
        -
          AttributeName: Timestamp
          KeyType: RANGE 
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ModelFunctionLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: lambdaModelFunction
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              -
                Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub ${PreparationBucket.Arn}/*
                  - !Sub ${ImageBucket.Arn}/*
              -
                Effect: Allow
                Action: dynamodb:PutItem
                Resource: !GetAtt OutputDatabase.Arn
      
  ModelFunctionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../lambda_functions/model_function/lambda_files/
      FunctionName: logoApplicationModelFunction
      Handler: lambda_function.lambda_handler
      Role: !GetAtt ModelFunctionLambdaRole.Arn
      Runtime: python3.6
      Environment: 
        Variables:
          TableName: !Ref OutputDatabase
          image_bucket: !Ref ImageBucket
          preparation_bucket: !Ref PreparationBucket
        